### ISSUE TITLE
Can't download yolo3 model

### ISSUE THREAD

**Issue by santutu** [carlosedubarreto/vibe_win_install#1]
When you command
`
python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display 
`
you will get FileNotFoundError Exception.

Because script try to download by wget linux command.
You have to  manually download yolo model from  
https://pjreddie.com/media/files/yolov3.weights
https://raw.githubusercontent.com/mkocabas/yolov3-pytorch/master/yolov3/config/yolov3.cfg

and place this files to
C:\Users\ {your user name} \ .torch\models\yolov3.weights
C:\Users\ {your user name} \ .torch\config\yolov3.cfg

**Comment by carlosedubarreto** [comment]
Hello @santutu ,

this part you are describing, is done in the "prepare_data.bat" file

as showed here
![image](https://user-images.githubusercontent.com/4061130/104118012-71d9b600-5304-11eb-8ed6-bc8d5830f691.png)


But I got feedback of people that could not run this batch file because it got stuck on the first line, where it downloads the file from
"https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r"

If this problem is happenning, I suggest to download the file mannually in the "data" folder and run the following batch (on the VIBE root folder)
[prepare_data_francis.zip](https://github.com/carlosedubarreto/vibe_win_install/files/5792395/prepare_data_francis.zip)
You'll have to unzip it on VIBE root folder.


The difference from this batch to the "prepare_data_bat" one is that the download command is commented (thats why I was sayign to download the file manually)

Seems like some PC antivirus was blocking the download.

**Comment by carlosedubarreto** [comment]
BTW, just an explanation about those yolo files.
The yolo3.weights is bundles inside the vibe_data.zip file that is downloaded on the beggining of the "prepare_data.zip"
and the yolov3.cfg is packed with this github repository, because it was easier to share it than adding another command on windows to download it, as I didnt find a better solution for windows, like the linux one, wget, that already comes with windows.
