### ISSUE TITLE
anaconda question

### ISSUE THREAD

**Issue by Christic9** [carlosedubarreto/vibe_win_install#22]
There is a question borthering me a lot:
I always having trouble on following pip install.This is a example
![捕获](https://user-images.githubusercontent.com/89370684/165443424-110b85d8-b516-4a11-9c81-f45dbd632c87.PNG)
I can not install all the package from github.how do i do to deal it?

**Comment by carlosedubarreto** [comment]
From the error, it seems that its a firewall problem

But there is another problem.
This instruction is so old, that maybe it wont work anymore.
What I suggest you is to take a look at the batch file in a notepad and try to follow manually what is done over there.

For example, the github part. you can download it manually and than run the command on the cmd prompt.

Its not the easiest neither the best option, but, its what I can give as idea, because it highly unlikely that I do an update for this instructions, sorry.

**Comment by Christic9** [comment]
Thank you so much.
You are so sweet.I deal this problem by directly downloading the zip program,and I manually install the yolov
3 and multipersontracker.
Thank you again.
Have a nice day!



| |
***@***.***
|
|
***@***.***
|




---- Replied mail ----
| From | Carlos ***@***.***> |
| Date | 04/27/2022 16:42 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [carlosedubarreto/vibe_win_install] anaconda question (Issue #22) |

From the error, it seems that its a firewall problem

But there is another problem.
This instruction is so old, that maybe it wont work anymore.
What I suggest you is to take a look at the batch file in a notepad and try to follow manually what is done over there.

For example, the github part. you can download it manually and than run the command on the cmd prompt.

Its not the easiest neither the best option, but, its what I can give as idea, because it highly unlikely that I do an update for this instructions, sorry.

**Comment by carlosedubarreto** [comment]
Thats great, and thanks for the information.
